# Pre-commit hooks for documentation quality
# Industry best practice: "Shift-left" validation (catch issues before CI)
#
# Install: pre-commit install
# Run manually: pre-commit run --all-files

repos:
  # MkDocs link validation (catches broken internal links)
  # Note: Warning-only mode during link cleanup (69 broken links found)
  # TODO: Enable strict mode after fixing broken links
  - repo: local
    hooks:
      - id: mkdocs-validate
        name: Validate MkDocs links (warning only)
        entry: bash -c 'uv run mkdocs build --site-dir /tmp/mkdocs-validate-$$ 2>&1; rm -rf /tmp/mkdocs-validate-$$; exit 0'
        language: system
        pass_filenames: false
        files: ^(docs/.*\.md|mkdocs\.yml)$
        description: Validates all documentation links (warnings shown but not blocking)

      - id: check-doc-links
        name: Check for absolute documentation URLs
        entry: .github/scripts/check-doc-links.sh
        language: system
        pass_filenames: false
        files: \.md$
        description: Prevents absolute aafc.devvyn.ca URLs (use relative links instead)

  # Python code quality (existing tools)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  # General file hygiene
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        exclude: ^(mkdocs\.yml|\.github/workflows/.*)$
      - id: check-added-large-files
        args: ['--maxkb=5000']  # Allow up to 5MB for data files in docs/
      - id: check-merge-conflict
