site_name: Herbarium DWC Extraction
site_description: Zero-cost AI-powered digitization for herbarium collections
site_url: https://aafc.devvyn.ca
repo_url: https://github.com/devvyn/aafc-herbarium-dwc-extraction-2025
repo_name: GitHub
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    # Light mode
    - scheme: default
      primary: green
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - scheme: slate
      primary: green
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.suggest
    - content.code.copy
    - content.action.edit
    - toc.follow
  icon:
    repo: fontawesome/brands/github
    logo: material/leaf

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - pymdownx.details
  - tables
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true

plugins:
  - search:
      lang: en
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago

extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/devvyn/aafc-herbarium-dwc-extraction-2025
    - icon: fontawesome/solid/leaf
      link: https://www.gbif.org
  analytics:
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve by
            <a href="https://github.com/devvyn/aafc-herbarium-dwc-extraction-2025/issues/new" target="_blank" rel="noopener">opening an issue</a>.

copyright: Copyright &copy; 2025 Agriculture and Agri-Food Canada (AAFC)

# Link validation (industry best practice - "docs as code")
validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn
  anchors: warn
