[project]
name = "herbarium-dwc"
version = "0.1.0"
description = "Herbarium OCR to Darwin Core extraction toolkit"
authors = [{name = "AAFC"}]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "typer",
    "pydantic",
    "Pillow",
    "numpy",
]

[project.scripts]
herbarium-dwc = "cli:app"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = [
    "config",
    "dwc",
    "engines",
    "io_utils",
    "qc",
    "preprocess",
]
py-modules = ["cli"]

[tool.hatch.build.targets.wheel.package-data]
config = ["config.default.toml", "rules/*.toml"]
engines = ["gpt/prompts/*"]

[dependency-groups]
dev = [
    "pytest>=8.4.1",
]

[tool.pytest.ini_options]
pythonpath = ["."]
