# Engines register themselves via the ``herbarium.engines`` entry-point group.
# Third-party packages can expose engines with:
# [project.entry-points."herbarium.engines"]
# name = "pkg.module"
# ``preferred_engine`` must correspond to a registered engine name.
[ocr]
preferred_engine = "vision"
# Engines can be limited via ``enabled_engines``.
# Example for running with only Vision installed:
# enabled_engines = ["vision"]
enabled_engines = ["vision", "tesseract", "gpt"]
allow_tesseract_on_macos = true
allow_gpt = true
confidence_threshold = 0.70

[gpt]
fallback_threshold = 0.85
dry_run = false
model = "gpt-4.1-mini"
prompt_dir = "prompts"

[tesseract]
oem = 1
psm = 6
langs = ["eng","fra","lat"]
extra_args = []

[pipeline]
steps = ["image_to_text", "text_to_dwc"]

[preprocess]
pipeline = ["grayscale", "deskew", "binarize", "resize"]
binarize_method = "adaptive"  # "otsu" or "adaptive"
max_dim_px = 4000
contrast_factor = 1.5  # used when "contrast" is in the pipeline

[dwc]
schema = "dwc-abcd"
schema_uri = "http://rs.tdwg.org/dwc/terms/"
schema_files = ["dwc.xsd", "abcd.xsd"]
assume_country_if_missing = "Canada"
strict_minimal_fields = ["catalogNumber","scientificName","eventDate","recordedBy","locality"]
flag_if_missing_minimal = true
parse_scientific_names = true
normalize_spelling = true
do_not_update_nomenclature = true

[gbif]
species_match_endpoint = "https://api.gbif.org/v1/species/match"
reverse_geocode_endpoint = "https://api.gbif.org/v1/geocode/reverse"

[qc]
dupes = ["catalog","sha256","phash"]
phash_threshold = 10
low_confidence_flag = true
top_fifth_scan_pct = 20

[report]
html = true

[processing]
retry_limit = 3
